# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Finn Gaida' do

pod 'PeekPop'
pod 'GradientView'
pod 'JTSImageViewController'

end

target 'Finn GaidaTests' do

end

